c_stdlib_version:  # [unix]
  - 2.17           # [linux]
  - 10.15          # [osx and x86_64]

MACOSX_SDK_VERSION:         # [osx]
  - 12.3                    # [osx]

blas_impl:
  - mkl                         # [x86_64]
  - generic

github_actions_labels:          # [linux]
- cirun-openstack-gpu-2xlarge   # [linux]

megabuild:
- true      # [linux]
- false     # [osx]

zip_keys:
  - - github_actions_labels
    - blas_impl

c_compiler:                 # [win]
- vs2019                    # [win]
cxx_compiler:               # [win]
- vs2019                    # [win]