c_stdlib:          # [linux64]
  - sysroot        # [linux64]

c_stdlib_version:  # [linux64 or (osx and x86_64)]
  - 2.17           # [linux64]
  - 10.15          # [osx and x86_64]

MACOSX_SDK_VERSION:         # [osx]
  - 12.3                    # [osx]

blas_impl:
  - mkl                         # [x86_64]
  - generic

github_actions_labels:          # [linux or win]
- cirun-openstack-gpu-2xlarge   # [linux]
- cirun-azure-windows-2xlarge   # [win]

megabuild:
- true      # [linux]
- false     # [osx]
- true      # [win]

# zip_keys:
#   - - github_actions_labels
#     - blas_impl