# for homogeneity with CUDA builds; can be deleted after
# https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/7421
c_compiler_version:         # [linux]
  - 14                      # [linux]
  - 14                      # [linux]
cxx_compiler_version:       # [linux]
  - 14                      # [linux]
  - 14                      # [linux]
fortran_compiler_version:   # [linux]
  - 14                      # [linux]
  - 14                      # [linux]
cuda_compiler_version:      # [linux]
  - None                    # [linux]
  - 12.6                    # [linux]

c_stdlib_version:  # [unix]
  - 10.15          # [osx and x86_64]

MACOSX_SDK_VERSION:         # [osx]
  - 13.3                    # [osx]

channel_targets:
  - conda-forge main
  - conda-forge pytorch_rc
is_rc:
  - False
  - True
zip_keys:
  -
    - channel_targets
    - is_rc

blas_impl:
  - mkl                         # [x86_64]
  # deprioritized on windows, would be nice to have
  - generic                     # [unix]

# https://github.com/conda-forge/.cirun
github_actions_labels:          # [linux or win]
- cirun-openstack-gpu-2xlarge   # [linux]
- cirun-azure-windows-2xlarge   # [win]

megabuild:
- true      # [linux]
- false     # [osx]
- true      # [win]
