c_stdlib_version:  # [unix]
  - 10.15          # [osx and x86_64]

MACOSX_SDK_VERSION:         # [osx]
  - 13.3                    # [osx]

blas_impl:
  - mkl                         # [x86_64]
  - generic

# https://github.com/conda-forge/.cirun
github_actions_labels:          # [linux]
- cirun-openstack-gpu-2xlarge   # [linux]

megabuild:
- true      # [linux]
- false     # [osx]

use_magma:
- true
- false
